GITHUB_TOKEN: ${ssm:GITHUB_TOKEN}
CHROMELESS_URL: ${ssm:CHROMELESS_URL}
CHROMELESS_APIKEY: ${ssm:CHROMELESS_APIKEY}
MYSQL_HOST: ${ssm:MYSQL_HOST_STG}
MYSQL_USER: ${ssm:MYSQL_USER_STG}
MYSQL_ROOT_PASSWORD: ${ssm:MYSQL_ROOT_PASSWORD_STG}
MYSQL_PORT: ${ssm:MYSQL_PORT_STG}
MYSQL_PORTFOLIOHUB_DATABASENAME: ${ssm:MYSQL_PORTFOLIOHUB_DATABASENAME}
APP_STORAGE: '/tmp'
ENV: local
BREF_BINARY_RESPONSES: 1
