GITHUB_TOKEN: ${ssm:GITHUB_TOKEN}
CHROMELESS_URL: ${ssm:CHROMELESS_URL}
CHROMELESS_APIKEY: ${ssm:CHROMELESS_APIKEY}
MYSQL_HOST: ${ssm:MYSQL_HOST_PROD}
MYSQL_USER: ${ssm:MYSQL_USER_PROD}
MYSQL_ROOT_PASSWORD: ${ssm:MYSQL_ROOT_PASSWORD_PROD}
MYSQL_PORT: ${ssm:MYSQL_PORT_PROD}
MYSQL_PORTFOLIOHUB_DATABASENAME: ${ssm:MYSQL_PORTFOLIOHUB_DATABASENAME}
APP_STORAGE: '/tmp'
ENV: prod
BREF_BINARY_RESPONSES: 1
BUCKET_NAME: storage.umihi.co
